spring:
  datasource:
    driver-Class-Name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/monique?serverTimezone=Asia/Tokyo
    username: monique
    password: 1234

    hikari:
      idle-timeout: 10000
      max-lifetime: 420000
      connection-timeout: 10000
      validation-timeout: 10000
